[package]
name = "catalyst-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "catalyst_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
# TODO: Use tag instead of path.
# catalyst-signed-doc = { version = "0.0.10", path = "../../rust/signed_doc" }
